Feat: Implement web-provider package
palladians/pallad pull request #140
Opened 2024-01-25 15:22 UTC by teddyjfpender

## Describe changes
To communicate with zkApps, Pallad must be able to receive requests and provide back data; Pallad must be able to talk! It must do so by following a specific pattern. A good implementation of the injected provider means developers spend little time integrating a wallet Pallad, and users of Pallad have granular control over what information they do and do not provide when their wallet receives a request.

This implementation is modelled around [EIP-1193](https://eips.ethereum.org/EIPS/eip-1193) with the `mina_` prefix instead of the `eth_` prefix.

Preliminary Mina-specific Tasks:
- [ ] add versioning of API
- [ ] `request` method 
    - [x] `mina_accounts` RPC Method
    - [x] `mina_sign` RPC Method
    - [x] `mina_signTransaction`  RPC Method
    - [x] `mina_signFields`  RPC Method
    - [x] `mina_signMessage` RPC Method (done in `mina_sign`)
    - [x] `mina_getBalance` RPC Method
    - [x]  `mina_chainId` RPC Method
    - [ ] `mina_sendTransaction` RPC Method
    - [ ] `mina_createNullifier` RPC Method
- [x] `enable` method
- [x] `connect` method
- [x] `disconnect` method
- [x] application listeners
    - [x] `on`
    - [x] `once`
    - [x] `removeListener`
    - [x] `off` 
- [ ] Correct event emitting
    - [ ] `accountsChanged`
    - [x] `chainChanged` 
- [x] Error handling 
    - [x] `4001`
    - [x] `4100`
    - [x] `4200`
    - [x] `4900`
    - [x]  `4901`
- [ ] Integrate into extension

Secondary Web3 Broad Tasks:
- [ ] Abstract over the `MinaProvider` to make a `UniversalProvider` for other ecosystems like Protoki, Zeko, Ethereum
- [ ] Add versioning

2024-01-28 18:54 UTC, teddyjfpender commented
pls review

2024-01-28 19:05 UTC, teddyjfpender commented
pls review

2024-01-28 19:15 UTC, teddyjfpender commented
pls review

2024-01-28 19:22 UTC, teddyjfpender commented
pls review

2024-01-30 16:15 UTC, mrcnk requested changes

2024-01-30 16:15 UTC, mrcnk commented on apps/extension/public/pallad_rpc.js
> +    console.log('callPalladAsync', method, payload)
remove logs pls

2024-01-30 16:15 UTC, mrcnk commented on packages/web-provider/src/vault-service/vault-service.ts
> +    console.log('signable: ', signable)
remove logs pls

2024-01-30 16:15 UTC, mrcnk commented on packages/web-provider/src/universal-provider/types.ts
> +import { EventEmitter } from 'events'
I'm not so sure we should add EventEmitter. It's nodejs native and we may get troubles in browser context. But if it works fine now, let it be.

2024-01-30 16:15 UTC, mrcnk commented on packages/web-provider/package.json
> +    "vitest": "^1.1.0"
Vitest should be in `devDependencies`.

2024-02-15 10:41 UTC, teddyjfpender commented
TODO: Complete e2e scenarios.

2024-02-15 10:41 UTC, merged